In [114]:
# helper functions for displaying table data

import numpy as np
from IPython.display import display_html

# n is the number of columns to display data in
def display_side_by_side(series_obj, n):
    df = pd.DataFrame(series_obj)
    partition = int(round(len(df) / n))
    lower_bound = 0
    upper_bound = partition
    args = []
    for i in range(n):
        args.append(df[lower_bound:upper_bound])
        lower_bound += partition
        upper_bound += partition
    helper(args)

def helper(args):
    html_str=''
    for df in args:
        html_str+=df.to_html()
    display_html(html_str.replace('table','table style="display:inline"'),raw=True)

In [115]:
import pandas as pd
pd.set_option('display.max_columns', 500)
import csv

# data: https://www.kaggle.com/muonneutrino/us-census-demographic-data#acs2017_county_data.csv
demographics = pd.read_csv("data/acs2017_county_data.csv")
demographics.head()

,CountyId,State,County,TotalPop,Men,Women,Hispanic,White,Black,Native,Asian,Pacific,VotingAgeCitizen,Income,IncomeErr,IncomePerCap,IncomePerCapErr,Poverty,ChildPoverty,Professional,Service,Office,Construction,Production,Drive,Carpool,Transit,Walk,OtherTransp,WorkAtHome,MeanCommute,Employed,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Unemployment
0,1001,Alabama,Autauga County,55036,26899,28137,2.7,75.4,18.9,0.3,0.9,0.0,41016,55317,2838,27824,2024,13.7,20.1,35.3,18.0,23.2,8.1,15.4,86.0,9.6,0.1,0.6,1.3,2.5,25.8,24112,74.1,20.2,5.6,0.1,5.2
1,1003,Alabama,Baldwin County,203360,99527,103833,4.4,83.1,9.5,0.8,0.7,0.0,155376,52562,1348,29364,735,11.8,16.1,35.7,18.2,25.6,9.7,10.8,84.7,7.6,0.1,0.8,1.1,5.6,27.0,89527,80.7,12.9,6.3,0.1,5.5
2,1005,Alabama,Barbour County,26201,13976,12225,4.2,45.7,47.8,0.2,0.6,0.0,20269,33368,2551,17561,798,27.2,44.9,25.0,16.8,22.6,11.5,24.1,83.4,11.1,0.3,2.2,1.7,1.3,23.4,8878,74.1,19.1,6.5,0.3,12.4
3,1007,Alabama,Bibb County,22580,12251,10329,2.4,74.6,22.0,0.4,0.0,0.0,17662,43404,3431,20911,1889,15.2,26.6,24.4,17.6,19.7,15.9,22.4,86.4,9.5,0.7,0.3,1.7,1.5,30.0,8171,76.0,17.4,6.3,0.3,8.2
4,1009,Alabama,Blount County,57667,28490,29177,9.0,87.4,1.5,0.3,0.1,0.0,42513,47412,2630,22021,850,15.6,25.4,28.5,12.9,23.3,15.8,19.5,86.8,10.2,0.1,0.4,0.4,2.1,35.0,21380,83.9,11.9,4.0,0.1,4.9

In [116]:
import us

demographics['State_Code'] = demographics.apply(lambda x: us.states.lookup(x['State']).abbr, axis=1)
demographics.head()

,CountyId,State,County,TotalPop,Men,Women,Hispanic,White,Black,Native,Asian,Pacific,VotingAgeCitizen,Income,IncomeErr,IncomePerCap,IncomePerCapErr,Poverty,ChildPoverty,Professional,Service,Office,Construction,Production,Drive,Carpool,Transit,Walk,OtherTransp,WorkAtHome,MeanCommute,Employed,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Unemployment,State_Code
0,1001,Alabama,Autauga County,55036,26899,28137,2.7,75.4,18.9,0.3,0.9,0.0,41016,55317,2838,27824,2024,13.7,20.1,35.3,18.0,23.2,8.1,15.4,86.0,9.6,0.1,0.6,1.3,2.5,25.8,24112,74.1,20.2,5.6,0.1,5.2,AL
1,1003,Alabama,Baldwin County,203360,99527,103833,4.4,83.1,9.5,0.8,0.7,0.0,155376,52562,1348,29364,735,11.8,16.1,35.7,18.2,25.6,9.7,10.8,84.7,7.6,0.1,0.8,1.1,5.6,27.0,89527,80.7,12.9,6.3,0.1,5.5,AL
2,1005,Alabama,Barbour County,26201,13976,12225,4.2,45.7,47.8,0.2,0.6,0.0,20269,33368,2551,17561,798,27.2,44.9,25.0,16.8,22.6,11.5,24.1,83.4,11.1,0.3,2.2,1.7,1.3,23.4,8878,74.1,19.1,6.5,0.3,12.4,AL
3,1007,Alabama,Bibb County,22580,12251,10329,2.4,74.6,22.0,0.4,0.0,0.0,17662,43404,3431,20911,1889,15.2,26.6,24.4,17.6,19.7,15.9,22.4,86.4,9.5,0.7,0.3,1.7,1.5,30.0,8171,76.0,17.4,6.3,0.3,8.2,AL
4,1009,Alabama,Blount County,57667,28490,29177,9.0,87.4,1.5,0.3,0.1,0.0,42513,47412,2630,22021,850,15.6,25.4,28.5,12.9,23.3,15.8,19.5,86.8,10.2,0.1,0.4,0.4,2.1,35.0,21380,83.9,11.9,4.0,0.1,4.9,AL

In [117]:
# data: https://www.kaggle.com/mikejohnsonjr/united-states-crime-rates-by-county
crime = pd.read_csv("data/crime_data_w_population_and_crime_rate.csv")
crime.head()

,county_name,crime_rate_per_100000,index,EDITION,PART,IDNO,CPOPARST,CPOPCRIM,AG_ARRST,AG_OFF,COVIND,INDEX,MODINDX,MURDER,RAPE,ROBBERY,AGASSLT,BURGLRY,LARCENY,MVTHEFT,ARSON,population,FIPS_ST,FIPS_CTY
0,"St. Louis city, MO",1791.995377,1,1,4,1612,318667,318667,15,15,100.0,5706,22329,119,200,1778,3609,4995,13791,3543,464,318416,29,510
1,"Crittenden County, AR",1754.914968,2,1,4,130,50717,50717,4,4,100.0,873,3424,8,38,165,662,1482,1753,189,28,49746,5,35
2,"Alexander County, IL",1664.700485,3,1,4,604,8040,8040,2,2,100.0,127,278,1,2,5,119,82,184,12,2,7629,17,3
3,"Kenedy County, TX",1456.310680,4,1,4,2681,444,444,1,1,100.0,6,13,0,3,1,2,5,4,4,0,412,48,261
4,"De Soto Parish, LA",1447.402430,5,1,4,1137,26971,26971,3,3,100.0,392,703,3,4,17,368,149,494,60,0,27083,22,31

In [118]:
cols_to_keep = ['county_name', 'crime_rate_per_100000', 'MURDER', 'RAPE', 'ROBBERY', 'BURGLRY', 'LARCENY',
               'ARSON']
crime = crime[cols_to_keep]
crime.head()

,county_name,crime_rate_per_100000,MURDER,RAPE,ROBBERY,BURGLRY,LARCENY,ARSON
0,"St. Louis city, MO",1791.995377,119,200,1778,4995,13791,464
1,"Crittenden County, AR",1754.914968,8,38,165,1482,1753,28
2,"Alexander County, IL",1664.700485,1,2,5,82,184,2
3,"Kenedy County, TX",1456.310680,0,3,1,5,4,0
4,"De Soto Parish, LA",1447.402430,3,4,17,149,494,0

In [119]:
# clean up crime county_name
temp = crime['county_name'].str.split(', ', expand=True)
crime['county_name'] = temp[0]
crime['state'] = temp[1]
crime.head()

,county_name,crime_rate_per_100000,MURDER,RAPE,ROBBERY,BURGLRY,LARCENY,ARSON,state
0,St. Louis city,1791.995377,119,200,1778,4995,13791,464,MO
1,Crittenden County,1754.914968,8,38,165,1482,1753,28,AR
2,Alexander County,1664.700485,1,2,5,82,184,2,IL
3,Kenedy County,1456.310680,0,3,1,5,4,0,TX
4,De Soto Parish,1447.402430,3,4,17,149,494,0,LA

In [120]:
crime_and_demographics = crime.merge(demographics, left_on='county_name', right_on='County')
crime_and_demographics.head()

,county_name,crime_rate_per_100000,MURDER,RAPE,ROBBERY,BURGLRY,LARCENY,ARSON,state,CountyId,State,County,TotalPop,Men,Women,Hispanic,White,Black,Native,Asian,Pacific,VotingAgeCitizen,Income,IncomeErr,IncomePerCap,IncomePerCapErr,Poverty,ChildPoverty,Professional,Service,Office,Construction,Production,Drive,Carpool,Transit,Walk,OtherTransp,WorkAtHome,MeanCommute,Employed,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Unemployment,State_Code
0,St. Louis city,1791.995377,119,200,1778,4995,13791,464,MO,29510,Missouri,St. Louis city,314867,152224,162643,3.9,42.9,47.5,0.2,3.1,0.0,241414,38664,799,26739,519,25.0,39.8,40.6,22.5,21.7,5.0,10.2,71.8,8.2,9.5,4.4,1.9,4.2,24.1,152079,83.9,11.8,4.0,0.2,9.4,MO
1,Crittenden County,1754.914968,8,38,165,1482,1753,28,AR,5035,Arkansas,Crittenden County,49278,23303,25975,2.4,43.2,48.9,0.3,0.7,0.1,35076,38558,3004,20721,665,23.5,37.0,29.4,18.4,23.1,10.2,18.8,82.1,10.1,0.3,1.7,2.4,3.4,19.9,20282,76.9,16.5,6.5,0.2,8.4,AR
2,Crittenden County,1754.914968,8,38,165,1482,1753,28,AR,21055,Kentucky,Crittenden County,9154,4627,4527,1.0,96.4,1.3,0.0,0.0,0.0,7000,41114,2805,22765,2086,17.7,25.4,28.3,17.5,18.3,14.3,21.6,77.9,13.0,0.8,2.8,1.5,3.9,24.5,3690,71.0,18.9,9.9,0.1,4.4,KY
3,Crittenden County,54.024851,0,1,1,27,73,0,KY,5035,Arkansas,Crittenden County,49278,23303,25975,2.4,43.2,48.9,0.3,0.7,0.1,35076,38558,3004,20721,665,23.5,37.0,29.4,18.4,23.1,10.2,18.8,82.1,10.1,0.3,1.7,2.4,3.4,19.9,20282,76.9,16.5,6.5,0.2,8.4,AR
4,Crittenden County,54.024851,0,1,1,27,73,0,KY,21055,Kentucky,Crittenden County,9154,4627,4527,1.0,96.4,1.3,0.0,0.0,0.0,7000,41114,2805,22765,2086,17.7,25.4,28.3,17.5,18.3,14.3,21.6,77.9,13.0,0.8,2.8,1.5,3.9,24.5,3690,71.0,18.9,9.9,0.1,4.4,KY

In [121]:
# check states match to increase likelihood of correct mapping
crime_and_demographics = crime_and_demographics[crime_and_demographics.State_Code == crime_and_demographics.state]
crime_and_demographics.drop(columns=['State_Code'], inplace=True)
crime_and_demographics.head()

,county_name,crime_rate_per_100000,MURDER,RAPE,ROBBERY,BURGLRY,LARCENY,ARSON,state,CountyId,State,County,TotalPop,Men,Women,Hispanic,White,Black,Native,Asian,Pacific,VotingAgeCitizen,Income,IncomeErr,IncomePerCap,IncomePerCapErr,Poverty,ChildPoverty,Professional,Service,Office,Construction,Production,Drive,Carpool,Transit,Walk,OtherTransp,WorkAtHome,MeanCommute,Employed,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Unemployment
0,St. Louis city,1791.995377,119,200,1778,4995,13791,464,MO,29510,Missouri,St. Louis city,314867,152224,162643,3.9,42.9,47.5,0.2,3.1,0.0,241414,38664,799,26739,519,25.0,39.8,40.6,22.5,21.7,5.0,10.2,71.8,8.2,9.5,4.4,1.9,4.2,24.1,152079,83.9,11.8,4.0,0.2,9.4
1,Crittenden County,1754.914968,8,38,165,1482,1753,28,AR,5035,Arkansas,Crittenden County,49278,23303,25975,2.4,43.2,48.9,0.3,0.7,0.1,35076,38558,3004,20721,665,23.5,37.0,29.4,18.4,23.1,10.2,18.8,82.1,10.1,0.3,1.7,2.4,3.4,19.9,20282,76.9,16.5,6.5,0.2,8.4
4,Crittenden County,54.024851,0,1,1,27,73,0,KY,21055,Kentucky,Crittenden County,9154,4627,4527,1.0,96.4,1.3,0.0,0.0,0.0,7000,41114,2805,22765,2086,17.7,25.4,28.3,17.5,18.3,14.3,21.6,77.9,13.0,0.8,2.8,1.5,3.9,24.5,3690,71.0,18.9,9.9,0.1,4.4
5,Alexander County,1664.700485,1,2,5,82,184,2,IL,17003,Illinois,Alexander County,6776,3258,3518,1.0,61.8,34.6,0.6,0.2,0.0,5100,31014,2759,18564,1678,33.4,59.3,26.8,27.8,25.9,4.9,14.6,87.7,5.8,0.8,1.7,1.4,2.6,27.3,2164,75.0,20.6,4.4,0.0,8.2
8,Alexander County,111.020850,2,7,7,371,560,16,NC,37003,North Carolina,Alexander County,37159,18797,18362,4.6,87.0,5.9,0.2,1.2,0.1,28548,44523,2886,22655,1043,14.7,23.6,26.8,12.6,20.6,9.4,30.7,84.9,8.9,0.0,0.8,2.6,2.8,25.6,16393,83.2,10.5,6.2,0.2,6.7

In [122]:
# calculate percentage of NaNs in each column
percent_missing = crime_and_demographics.isnull().sum() * 100 / len(crime_and_demographics)
missing_value_df = pd.DataFrame({'column_name': crime_and_demographics.columns,'percent_missing': percent_missing})

display_side_by_side(missing_value_df, 2)

,column_name,percent_missing
county_name,county_name,0.0
crime_rate_per_100000,crime_rate_per_100000,0.0
MURDER,MURDER,0.0
RAPE,RAPE,0.0
ROBBERY,ROBBERY,0.0
BURGLRY,BURGLRY,0.0
LARCENY,LARCENY,0.0
ARSON,ARSON,0.0
state,state,0.0
CountyId,CountyId,0.0
State,State,0.0
County,County,0.0
TotalPop,TotalPop,0.0
Men,Men,0.0
Women,Women,0.0
Hispanic,Hispanic,0.0
White,White,0.0
Black,Black,0.0
Native,Native,0.0
Asian,Asian,0.0
Pacific,Pacific,0.0
VotingAgeCitizen,VotingAgeCitizen,0.0
Income,Income,0.0
,column_name,percent_missing
IncomeErr,IncomeErr,0.000000
IncomePerCap,IncomePerCap,0.000000
IncomePerCapErr,IncomePerCapErr,0.000000
Poverty,Poverty,0.000000
ChildPoverty,ChildPoverty,0.031928
Professional,Professional,0.000000
Service,Service,0.000000
Office,Office,0.000000
Construction,Construction,0.000000
Production,Production,0.000000
Drive,Drive,0.000000
Carpool,Carpool,0.000000
Transit,Transit,0.000000
Walk,Walk,0.000000
OtherTransp,OtherTransp,0.000000
WorkAtHome,WorkAtHome,0.000000
MeanCommute,MeanCommute,0.000000
Employed,Employed,0.000000
PrivateWork,PrivateWork,0.000000
PublicWork,PublicWork,0.000000
SelfEmployed,SelfEmployed,0.000000
FamilyWork,FamilyWork,0.000000
Unemployment,Unemployment,0.000000

In [123]:
crime_and_demographics.drop(columns=['ChildPoverty'], inplace=True)

# calculate percentage of NaNs in each column
percent_missing = crime_and_demographics.isnull().sum() * 100 / len(crime_and_demographics)
missing_value_df = pd.DataFrame({'column_name': crime_and_demographics.columns,'percent_missing': percent_missing})

display_side_by_side(missing_value_df, 2)

,column_name,percent_missing
county_name,county_name,0.0
crime_rate_per_100000,crime_rate_per_100000,0.0
MURDER,MURDER,0.0
RAPE,RAPE,0.0
ROBBERY,ROBBERY,0.0
BURGLRY,BURGLRY,0.0
LARCENY,LARCENY,0.0
ARSON,ARSON,0.0
state,state,0.0
CountyId,CountyId,0.0
State,State,0.0
County,County,0.0
TotalPop,TotalPop,0.0
Men,Men,0.0
Women,Women,0.0
Hispanic,Hispanic,0.0
White,White,0.0
Black,Black,0.0
Native,Native,0.0
Asian,Asian,0.0
Pacific,Pacific,0.0
VotingAgeCitizen,VotingAgeCitizen,0.0
,column_name,percent_missing
Income,Income,0.0
IncomeErr,IncomeErr,0.0
IncomePerCap,IncomePerCap,0.0
IncomePerCapErr,IncomePerCapErr,0.0
Poverty,Poverty,0.0
Professional,Professional,0.0
Service,Service,0.0
Office,Office,0.0
Construction,Construction,0.0
Production,Production,0.0
Drive,Drive,0.0
Carpool,Carpool,0.0
Transit,Transit,0.0
Walk,Walk,0.0
OtherTransp,OtherTransp,0.0
WorkAtHome,WorkAtHome,0.0
MeanCommute,MeanCommute,0.0
Employed,Employed,0.0
PrivateWork,PrivateWork,0.0
PublicWork,PublicWork,0.0
SelfEmployed,SelfEmployed,0.0
FamilyWork,FamilyWork,0.0